# Generated by Django 5.0.4 on 2024-04-27 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('items', '0002_auto_20240427_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='title',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='items.item'),
        ),
    ]
