# Generated by Django 5.0.4 on 2024-04-27 03:03

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('items', 'Category')
    category_list = [
        '전자기기',
        '가구',
        '의류',
        '스포츠용품',
        '책',
    ]

    for cat_name in category_list:
        Category.objects.create(name=cat_name)


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
